#!/bin/bash
d="`mktemp -d`"
(
  cd "$d"
  [ -f whatsapp.ab ] || adb backup -f whatsapp.ab -noapk com.whatsapp
  dd if=whatsapp.ab bs=1 skip=24 | python -c "import zlib,sys;sys.stdout.write(zlib.decompress(sys.stdin.read()))" | tar x
  adb push apps/com.whatsapp/f/key /sdcard/WhatsApp/Databases/.nomedia
)
rm -r "$d"
